# lavaurl=http://localhost
# adminuser=admin
# adminpass=admin
# devicename=dummy-host-1
# devicetype=dummy-host

lavaurl=http://localhost
adminuser=$1
adminpass=$2
devicetype=$3
devicename=$4


#obtain the csrf token
data=$(curl -s -c cookies.txt $lavaurl/accounts/login/  | grep -o "name=['\"]csrfmiddlewaretoken['\"] value=['\"][^'\"]*" | sed -e "s/name='//" -e "s/' value='/=/")

#login
login=$data\&username=$adminuser\&password=$adminpass
curl -b cookies.txt -c cookies.txt -d $login -X POST $lavaurl/accounts/login/

#create an api key
createapi=$data\&description=autogenerated
curl -b cookies.txt -c cookies.txt -d $createapi -X POST $lavaurl/api/tokens/create/

# configure device type and device
# Add new device type "qemu"
## http://localhost/admin/lava_scheduler_app/devicetype/add/
createdevicetype=$data\&name=$devicetype\&display=1
curl -b cookies.txt -c cookies.txt -d $createdevicetype -X POST $lavaurl/admin/lava_scheduler_app/devicetype/add/

# Add new device "qemu01" of device type "qemu"
## http://localhost/admin/lava_scheduler_app/device/add/
createdevice=$data\&hostname=$devicename\&device_type=$devicetype\&device_version=1\&status=1\&health_status=0
curl -b cookies.txt -c cookies.txt -d $createdevice -X POST $lavaurl/admin/lava_scheduler_app/device/add/
