#!/usr/bin/env bash
#
# deployment script for LAVA job submission
# Version v0.1.0
# More info: 
#
# Copyright (c) 2014 Linaro, LTD
# http://www.linaro.org
#
#

### Configuration
#####################################################################
domain=$1
url=http://localhost:80
workdir=/opt/simpledeploy/$domain

webproject=kernel-ci-frontend
webrepo=http://git.linaro.org/infrastructure/kernel-ci-frontend.git
webdir=$workdir/$webproject

webdata=$webdir/www
teststring=Automated


### Dependencies
#####################################################################

### Functions
#####################################################################

### Runtime
#####################################################################


### perform simple test to check install was successful
#####################################################################
curl $url
curl -o test $url
lava-test-case http-server-verification --shell grep $teststring test
