#!/bin/bash

apt-get -y update
apt-get -y install build-essential cmake ninja-build git libedit-dev ncurses-dev python-dev swig clang-3.5 ccache binutils-gold php5-curl
apt-get -y install libxml2-dev libxslt1-dev doxygen 

cat > $HOME/lldb-setup.sh <<EOL
#!/bin/bash
ROOT_DIR=$HOME/ll/googd
mkdir -p $ROOT_DIR
cd $ROOT_DIR
git clone http://github.com/tfiala/lldb.git
(cd lldb && git checkout dev-thread-state-coordinator)
git clone http://llvm.org/git/llvm.git
(cd llvm && git checkout f93662d3d5a61c8f166db48614faa7b92f98c4c8)
git clone http://llvm.org/git/clang.git
(cd clang && git checkout bcf4a38dff586edf03de97371289b19e1618ddf9)
git clone http://github.com/tfiala/lldb-tools
cd llvm/tools
ln -s ../../clang clang
ln -s ../../lldb lldb
cd $ROOT_DIR
mkdir -p build/host
cd build/host
cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_LINKER=ld.gold -DCMAKE_BUILD_TYPE=Debug ../../llvm
# use lldb-gdbserver when debugging local processes
export PLATFORM_LINUX_FORCE_LLGS_LOCAL=1
ninja && ninja check-lldb
EOL

. ~/lldb-setup
