#!/usr/bin/env bash
#
# linaro-jenkins-tools Ansible deployment script for LAVA job submission
# Version v0.1.0
# More info: 
#
# Copyright (c) 2014 Linaro, LTD
# http://www.linaro.org
#
# Usage:
#  ./linaro-jenkins-tools.sh domainname
#

### Configuration
#####################################################################

domain=$1
playbook=https://git.linaro.org/infrastructure/linaro-jenkins-tools.git
workdir=ansible


### Functions
#####################################################################

### Runtime
#####################################################################

# running on a KVM requires a bit more memory
dd if=/dev/zero of=/swap bs=1M count=1000
mkswap /swap
swapon /swap

# Download playbook into a persistent location
mkdir -p /opt; cd /opt
git clone ${playbook} ${workdir}
cd ${workdir}/ansible

#execute playbook
echo "### Executing ansible-playbook"
ansible-playbook -c local -i hosts-devel-tcwg-ci -l "tcwg-ci:&vagrant" site.yml

#Wait for services
echo "sleep 90"
sleep 90

# Check for exceptions in the log file
echo "Exceptions in log file"
echo "=============================="
grep IOException /var/log/jenkins/jenkins.log

echo "Initial LOG File"
echo "Initialization LOG"
echo "=============================="
cat /var/log/jenkins/jenkins.log

#restart jenkins service
#service jenkins restart

#run some LAVA api tests to see if the server is up
curl -o test http://localhost:8080
lava-test-case http-server-verification --shell grep Authentication test

curl -X POST http://localhost:8080 --user admin:admin -o test
lava-test-case jenkins-login --shell grep Dashboard test

wget http://localhost:8080/jnlpJars/jenkins-cli.jar
java -jar jenkins-cli.jar -s http://admin:admin@localhost:8080/ list-plugins
